# Numpy

для матричных вычислений

Python Numpy Tutorial
http://cs231n.github.io/python-numpy-tutorial/

In [2]:
import numpy as np

In [7]:
array = np.array([1,2,4,5])
print(array)
print("shape: {}".format(array.shape))

[1 2 4 5]
shape: (4,)


всё нумеруется с нуля

In [8]:
print(array[0], array[1], array[2])
print(array[:3])


1 2 4
[1 2 4]


In [9]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print("shape: {}".format(b.shape))                
print("work with indecies:", b[0], b[0, 1], b[:, 0]) 
print("slicing: {}".format(b[0, :2]))

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
work with indecies: [1 2 3] 2 [1 4]
slicing: [1 2]


создание спецефичных матриц

In [10]:
a = np.zeros((2,2))
print(a)

b = np.ones((1,2))
print(b) 

[[0. 0.]
 [0. 0.]]
[[1. 1.]]


In [11]:
a + b

array([[1., 1.],
       [1., 1.]])

# Pandas

для работы с табличными данными

http://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

In [2]:
import pandas as pd

In [32]:
df = pd.read_csv('data/kickstarter/ks-projects-201612.csv', encoding='Windows-1252')

/home/olga/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [43]:
df.head()

ID                                               name   \
0  1000002330                    The Songs of Adelaide & Abullah   
1  1000004038                                     Where is Hank?   
2  1000007540  ToshiCapital Rekordz Needs Help to Complete Album   
3  1000011046  Community Film Project: The Art of Neighborhoo...   
4  1000014025                               Monarch Espresso Bar   

        category  main_category  currency             deadline   goal   \
0          Poetry     Publishing       GBP  2015-10-09 11:36:00   1000   
1  Narrative Film   Film & Video       USD  2013-02-26 00:20:50  45000   
2           Music          Music       USD  2012-04-16 04:24:11   5000   
3    Film & Video   Film & Video       USD  2015-08-29 01:00:00  19500   
4     Restaurants           Food       USD  2016-04-01 13:38:27  50000   

             launched  pledged       state  backers  country  usd pledged   \
0  2015-08-11 12:12:28        0      failed        0       GB            0   
1  2013-01-12 00:20:50      220      failed        3       US          220   
2  2012-03-17 03:24:11        1      failed        1       US            1   
3  2015-07-04 08:35:03     1283    canceled       14       US         1283   
4  2016-02-26 13:38:27    52375  successful      224       US        52375   

  Unnamed: 13 Unnamed: 14 Unnamed: 15  Unnamed: 16  
0         NaN         NaN         NaN          NaN  
1         NaN         NaN         NaN          NaN  
2         NaN         NaN         NaN          NaN  
3         NaN         NaN         NaN          NaN  
4         NaN         NaN         NaN          NaN

In [44]:
print(df.shape)

(323750, 17)


In [45]:
print(df.columns)

Index(['ID ', 'name ', 'category ', 'main_category ', 'currency ', 'deadline ',
       'goal ', 'launched ', 'pledged ', 'state ', 'backers ', 'country ',
       'usd pledged ', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16'],
      dtype='object')


In [46]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 323750 entries, 0 to 323749
Data columns (total 17 columns):
ID                323750 non-null int64
name              323746 non-null object
category          323745 non-null object
main_category     323750 non-null object
currency          323750 non-null object
deadline          323750 non-null object
goal              323750 non-null object
launched          323750 non-null object
pledged           323750 non-null object
state             323750 non-null object
backers           323750 non-null object
country           323750 non-null object
usd pledged       319960 non-null object
Unnamed: 13       625 non-null object
Unnamed: 14       12 non-null object
Unnamed: 15       4 non-null object
Unnamed: 16       1 non-null float64
dtypes: float64(1), int64(1), object(15)
memory usage: 42.0+ MB
None


In [47]:
df.describe()

ID   Unnamed: 16
count  3.237500e+05          1.0
mean   1.074943e+09         25.0
std    6.193352e+08          NaN
min    5.971000e+03         25.0
25%    5.375802e+08         25.0
50%    1.075818e+09         25.0
75%    1.611070e+09         25.0
max    2.147476e+09         25.0

In [48]:
df.describe(include=['object', 'bool'])

name        category  main_category  currency   \
count                     323746          323745         323750    323750   
unique                    321612             770            120        37   
top     New EP/Music Development  Product Design   Film & Video       USD   
freq                          41           17477          57679    260298   

       deadline    goal  launched  pledged   state  backers  country   \
count     323750  323750    323750   323750  323750   323750   323750   
unique    294813    8188    322798    55598     410     3592      162   
top          USD    5000      5000        0  failed        0       US   
freq         508   25520        60    45784  168221    48863   257565   

       usd pledged  Unnamed: 13 Unnamed: 14 Unnamed: 15  
count        319960         625          12           4  
unique        94376         436           8           4  
top               0           0           1           0  
freq          50462          69           3           1

In [49]:
df['main_category'].value_counts()

# df['main_category'].value_counts(normalize=True)

KeyError: 'main_category'

In [41]:
df.sort_values(by='usd pledged', ascending=False).head()

KeyError: 'usd pledged'

In [22]:
df['usd pledged'].mean()

7036.728867109212

In [23]:
df[-3:]

ID                                               name  \
378658  999986353  Walls of Remedy- New lesbian Romantic Comedy f...   
378659  999987933                           BioDefense Education Kit   
378660  999988282                  Nou Renmen Ayiti!  We Love Haiti!   

               category main_category currency    deadline     goal  \
378658   Narrative Film  Film & Video      USD  2010-08-16  15000.0   
378659       Technology    Technology      USD  2016-02-13  15000.0   
378660  Performance Art           Art      USD  2011-08-16   2000.0   

                   launched  pledged   state  backers country  usd pledged  \
378658  2010-07-01 19:40:30     20.0  failed        1      US         20.0   
378659  2016-01-13 18:13:53    200.0  failed        6      US        200.0   
378660  2011-07-19 09:07:47    524.0  failed       17      US        524.0   

        usd_pledged_real  usd_goal_real  
378658              20.0        15000.0  
378659             200.0        15000.0  
378660             524.0         2000.0

In [28]:
len(df["main_category"].values)

378661