numpy - библиотека для работы с числовыми матрицами. 

В ней реализованы многие матричные операции.

Написана на C++

In [31]:
import numpy as np
from sklearn import datasets


# 1. Создание матриц

### 1.1 из стандартных типов данных

my_list = [1,2,3,4,5,6]
my_array = np.array(my_list)

print(my_array)
print(my_array.shape)
print(type(my_array))

In [6]:
my_list = [[1,2],[3,4],[5,6]]
my_array = np.array(my_list)

print(my_array)
print(my_array.shape)
print(type(my_array))

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
<class 'numpy.ndarray'>


в массиве можно хранить разные вещи - но операции с ними будут не оптимальны

In [22]:
my_list = [[1,2],[3,4],[5,6], {1:4}]
my_array = np.array(my_list)

print(my_array)
print(my_array.shape)
print(type(my_array))
print(my_array.dtype)

[list([1, 2]) list([3, 4]) list([5, 6]) {1: 4}]
(4,)
<class 'numpy.ndarray'>
object


не надо так делать

### 1.2 Можно создавать специяльные матрицы

In [15]:
my_array = np.zeros((3,4))

print(my_array)
print(my_array.shape)
print(type(my_array))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
<class 'numpy.ndarray'>


In [20]:
my_array = np.ones(2)

print(my_array)
print(my_array.shape)
print(type(my_array))
print(my_array.dtype)

[1. 1.]
(2,)
<class 'numpy.ndarray'>
float64


In [19]:
my_array = np.identity(3)

print(my_array)
print(my_array.shape)
print(type(my_array))
print(my_array.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
<class 'numpy.ndarray'>
float64


In [23]:
my_array = np.linspace(1,5,100)

print(my_array)
print(my_array.shape)
print(type(my_array))
print(my_array.dtype)

[1.         1.04040404 1.08080808 1.12121212 1.16161616 1.2020202
 1.24242424 1.28282828 1.32323232 1.36363636 1.4040404  1.44444444
 1.48484848 1.52525253 1.56565657 1.60606061 1.64646465 1.68686869
 1.72727273 1.76767677 1.80808081 1.84848485 1.88888889 1.92929293
 1.96969697 2.01010101 2.05050505 2.09090909 2.13131313 2.17171717
 2.21212121 2.25252525 2.29292929 2.33333333 2.37373737 2.41414141
 2.45454545 2.49494949 2.53535354 2.57575758 2.61616162 2.65656566
 2.6969697  2.73737374 2.77777778 2.81818182 2.85858586 2.8989899
 2.93939394 2.97979798 3.02020202 3.06060606 3.1010101  3.14141414
 3.18181818 3.22222222 3.26262626 3.3030303  3.34343434 3.38383838
 3.42424242 3.46464646 3.50505051 3.54545455 3.58585859 3.62626263
 3.66666667 3.70707071 3.74747475 3.78787879 3.82828283 3.86868687
 3.90909091 3.94949495 3.98989899 4.03030303 4.07070707 4.11111111
 4.15151515 4.19191919 4.23232323 4.27272727 4.31313131 4.35353535
 4.39393939 4.43434343 4.47474747 4.51515152 4.55555556 4.595959

linspace используется для отрисовки графиков функций - с его помощью мы задаем значения $x$ в которых будем считать $y$

In [47]:
my_array = np.arange(10) # аналог стандортного range

print(my_array)
print(my_array.shape)
print(type(my_array))
print(my_array.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,)
<class 'numpy.ndarray'>
int64


arange очень часто встречается вместе с reshape

In [71]:
my_array = np.arange(1,11)
my_array = my_array.reshape(5,2)
# my_array = my_array.reshape(5,-1)

print(my_array)
print(my_array.shape)
print(type(my_array))
print(my_array.dtype)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)
<class 'numpy.ndarray'>
int64


### 1.3 Можно считать таблицу из файла

In [32]:
iris = datasets.load_iris()

In [39]:
print(type(iris.data))
print(iris.data.shape)
print("data:")
print(iris.data[:5])

<class 'numpy.ndarray'>
(150, 4)
data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [49]:
np.savetxt('test.csv', iris.data, delimiter=',')

In [125]:
data_iris_loaded = np.loadtxt('test.csv', delimiter=',')

In [54]:
(iris.data - data_iris_loaded == 0).all()

True

# 2 Проверки матриц

испортим матрицу

In [59]:
data_iris_loaded[0,1] = np.nan
data_iris_loaded[10,3] = None
data_iris_loaded[5,2] = np.inf

In [61]:
np.isnan(data_iris_loaded)

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
 

In [62]:
np.isnan(data_iris_loaded).any()

True

In [67]:
data_iris_loaded = np.nan_to_num(data_iris_loaded)
# Replace NaN with zero and infinity with large finite numbers.

Почти все команды numpy не меняют исходную матрицу. Они возвращают результат применения команды, исходная матрица остается неизменной

# 3 Матричные опериции

In [91]:
m1 = np.arange(6).reshape(3, -1)
m2 = np.arange(12).reshape(4, -1)
vec1 = np.array([1,2,3])
vec2 = np.array([2,1])

перемножение матриц:

In [92]:
print(m2)
print(m1)
print(m2@m1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]


In [93]:
print(m1)
print(vec1@m1)

[[0 1]
 [2 3]
 [4 5]]
[16 22]


pointwise умножение

In [94]:
m1*m1

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [95]:
m1*vec2

array([[0, 1],
       [4, 3],
       [8, 5]])

In [96]:
m1+vec2

array([[2, 2],
       [4, 4],
       [6, 6]])

In [87]:
m2 + vec1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# 4 Selector-ы, фильтрация

## 4.1 Slice

In [126]:
tmp = data_iris_loaded[0:10, 0:2].copy()

In [129]:
tmp

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1]])

In [128]:
data_iris_loaded[:10, :2] = 0 
data_iris_loaded

array([[0. , 0. , 1.4, 0.2],
       [0. , 0. , 1.4, 0.2],
       [0. , 0. , 1.3, 0.2],
       [0. , 0. , 1.5, 0.2],
       [0. , 0. , 1.4, 0.2],
       [0. , 0. , 1.7, 0.4],
       [0. , 0. , 1.4, 0.3],
       [0. , 0. , 1.5, 0.2],
       [0. , 0. , 1.4, 0.2],
       [0. , 0. , 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [130]:
data_iris_loaded[:10, :2] = tmp
data_iris_loaded

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

### 4.2 Selector

In [136]:
selector_1 = data_iris_loaded[:, 1] > 3
selector_1

array([ True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False, False,  True, False,
        True, False, False,  True, False, False, False,  True,  True,
       False, False,

как много значений удоблетворяют требованиям?

In [140]:
# np.sum(selector_1)
np.count_nonzero(selector_1)

67

выделим объекты, удовлетворяющие требованию "перый признак > 3" в отдельны массив

In [135]:
selected_data = data_iris_loaded[Selector_1]
selected_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3

# Немного  стандартных функций

In [142]:
np.mean(selected_data,axis=0)

array([5.68358209, 3.43432836, 2.93432836, 0.90746269])

In [145]:
np.std(selected_data,axis=1)

array([1.88745861, 1.72988439, 1.65604952, 1.86748494, 1.93196791,
       1.67686463, 1.82671153, 1.79164729, 1.99874961, 1.74642492,
       2.22261108, 2.13658606, 1.99812412, 1.85657615, 2.05228531,
       1.88198698, 1.93826598, 1.83626659, 1.80762275, 1.7284386 ,
       1.71227188, 1.74928557, 1.9065676 , 1.90984293, 1.68874954,
       1.71227188, 1.90443561, 2.02530862, 2.1194044 , 1.75979402,
       1.8493242 , 2.04129248, 1.86681547, 1.86077941, 1.83898749,
       1.62999233, 1.69908063, 1.79304211, 1.89917745, 1.68151717,
       1.96516539, 1.82944664, 2.0535031 , 1.79304211, 2.01494417,
       1.73403431, 1.93520025, 1.55784306, 1.60526478, 1.92613603,
       1.65283847, 1.88215302, 1.72771525, 1.62941707, 2.20340645,
       1.85253205, 1.83507493, 2.15116248, 2.28076193, 1.58488959,
       1.83711731, 1.88596792, 1.7613915 , 1.79094947, 1.85539753,
       1.71099386, 1.55141065])

In [144]:
np.sum(selected_data)

868.3000000000001